const questions = [
  { q: "Identified six categories of activities of business", options: ["Peter Drucker", "Terry", "Henri Fayol", "Taylor"], answer: "Henri Fayol" },
  { q: "Major objective of business is", options: ["Profit", "Service", "Advertising", "Insurance"], answer: "Profit" },
  { q: "Which of the following is not an activity of business?", options: ["Technical activities", "Commercial activities", "Personnel activities", "Managerial and Administrative activities"], answer: "Personnel activities" },
  { q: "The activities that deals with production of goods and services is", options: ["Technical activities", "Financial activities", "Security activities", "Administrative activities"], answer: "Technical activities" },
  { q: "Business process starts with", options: ["Production of satisfying goods", "Acquisition of productive resources", "Identification of customers need", "Collection of revenue from sales"], answer: "Identification of customers need" },
  { q: "No business organisation operates in vacuum. Which is not a resource needed?", options: ["Capital", "Human resources", "Natural resources", "None of the above"], answer: "None of the above" },
  { q: "Objectives of business include", options: ["Marketing standing", "Productivity", "Innovation", "All of the above"], answer: "All of the above" },
  { q: "Evolution of business started with which Industrial Revolution?", options: ["1780", "1760", "1670", "1435"], answer: "1760" },
  { q: "Industrial Revolution aimed at", options: ["Mass production by semi-skilled labour aided by machine", "Producing more goods faster", "Advancement in technology and increase in demand for manufactured goods", "Consumer orientation"], answer: "Mass production by semi-skilled labour aided by machine" },
  { q: "Industrial Entrepreneur occurred in", options: ["Late 1800", "Early 1800", "Late 1700", "Early 1700"], answer: "Late 1800" },
  { q: "Evolution of business occurred with the following eras except", options: ["Production Era", "Industrial Revolution Era", "Relationship Era", "Selling Era", "None of the above"], answer: "None of the above" },
  { q: "Production Era was in which decade?", options: ["1920s", "1930s", "1940s", "1830s"], answer: "1920s" },
  { q: "Era centered on benefits derived from deep ongoing links with individuals", options: ["Relationship Era", "Industrial Revolution", "Industrial Entrepreneur", "Marketing Era"], answer: "Relationship Era" },
  { q: "Function concerned with transformation of raw materials into output", options: ["Production management function", "Personnel function", "Finance function", "Marketing function"], answer: "Production management function" },
  { q: "Systematic production management to transform resources effectively is", options: ["Industrial Function", "Marketing Function", "Production Management Function", "Human Resources Function"], answer: "Production Management Function" },
  { q: "Control mechanism starts with", options: ["Output", "Production", "Inputs/resources", "Advertising"], answer: "Inputs/resources" },
  { q: "Rules, regulations, and laws affecting business activities are called", options: ["Cultural environment", "Legal environment", "Technology environment", "Social environment"], answer: "Legal environment" },
  { q: "Which is not an environment of business enterprise?", options: ["Resources environment", "Economic environment", "Labour environment", "Infrastructural environment"], answer: "Resources environment" },
  { q: "Which is not a type of production?", options: ["Batch", "Micro", "Mass", "Job"], answer: "Micro" },
  { q: "Carrying out jobs individually according to specific order of customer is", options: ["Batch production", "Process production", "Job production", "Mass production"], answer: "Job production" },
  { q: "Mass production is also known as", options: ["Flow line production", "Job production", "Batch production", "Process production"], answer: "Flow line production" },
  { q: "Production between jobbing and mass production is", options: ["Process production", "Batch production", "Mass production", "Job production"], answer: "Batch production" },
  { q: "Production for stock and to meet specific orders is", options: ["Job Production", "Mass Production", "Process Production", "Batch Production"], answer: "Batch Production" },
  { q: "Production that saves cost for organization is", options: ["Process Production", "Batch Production", "Job Production", "Mass Production"], answer: "Batch Production" },
  { q: "Production of large quantities of identical goods continuously is", options: ["Mass Production", "Job Production", "Batch Production", "Process Production"], answer: "Mass Production" },
  { q: "Production using automated complex technology is", options: ["Process Production", "Batch Production", "Job Production", "Mass Production"], answer: "Process Production" },
  { q: "Aspect concerned with planning and regulation of production operations is", options: ["Production Management", "Production Planning", "Production Administration", "Production Function"], answer: "Production Administration" },
  { q: "Production Administration includes except", options: ["Production Engineering", "Production Planning", "Production Control", "None of the above"], answer: "None of the above" },
  { q: "Covers design of work methods and work standard", options: ["Method Study", "Work Study", "Time Study", "None of the above"], answer: "Work Study" },
  { q: "Establishing optimum work methods is", options: ["Method Study", "Work Study", "Plan Study", "None of the above"], answer: "Method Study" },
  { q: "Techniques to establish time for a job at defined performance is", options: ["Performance measurement", "Work measurement", "Time measurement", "Method measurement"], answer: "Work measurement" },
  { q: "Which is not among 6P's of Production?", options: ["Product", "Plan", "Project", "Program"], answer: "Plan" },
  { q: "Process where material inputs are transformed to outputs with different characteristics", options: ["Assembly Process", "Transformation Process", "Synthetic Process", "Fabrication Process"], answer: "Transformation Process" },
  { q: "Process where raw material produces outputs of same substance but different features", options: ["Fabrication Process", "Synthetic Process", "Transformation Process", "Inspection Process"], answer: "Fabrication Process" },
  { q: "Materials put together in solid state to produce objects without losing substance", options: ["Extractive Process", "Fabrication Process", "Synthetic Process", "Assembly Process"], answer: "Assembly Process" },
  { q: "Ability to use resources efficiently to achieve goals is", options: ["Planning", "Productivity", "Analysis", "Process"], answer: "Productivity" },
  { q: "Ratio of output to organizational inputs is", options: ["Output", "Resources", "Productivity", "Planning"], answer: "Productivity" },
  { q: "Productivity measured per input of resources is", options: ["Factor/Partial Productivity", "Total Productivity", "Material Production", "Micro Production"], answer: "Factor/Partial Productivity" },
  { q: "Total productivity is measured through", options: ["Minimum resources", "Maximum resources", "Input value", "Collection of all factors of production"], answer: "Collection of all factors of production" },
  { q: "Factors affecting productivity include", options: ["Innovation & Technological factor", "Scarcity of infrastructural facilities", "Level of R&D", "All of the above"], answer: "All of the above" },
  { q: "Study of productivity over time is called", options: ["Trend Analysis", "Vertical Analysis", "Horizontal Analysis", "Budgetary Analysis"], answer: "Trend Analysis" },
  { q: "Comparison of productivity with other industries/firms is called", options: ["Budgetary Analysis", "Vertical Analysis", "Horizontal Analysis", "Trend Analysis"], answer: "Vertical Analysis" },
  { q: "Investigation activities to develop or improve products is", options: ["Development", "Research", "Analysis", "Evaluation"], answer: "Research" },
  { q: "Function ensuring funds are available for activities is", options: ["Financial Function", "Personnel Function", "Production Function", "Legal Function"], answer: "Financial Function" },
  { q: "Financial manager responsibilities except", options: ["Retention of Profits", "Ensures fund is available", "Investing in right assets", "None of the above"], answer: "None of the above" },
  { q: "Two main sources of finance are", options: ["Macro & Micro", "Internal & External", "Local & Foreign", "None of the above"], answer: "Internal & External" },
  { q: "External source of finance includes", options: ["Short term finance", "Middle term finance", "Long term finance", "All of the above"], answer: "All of the above" },
  { q: "Retention of profits is", options: ["Internal source", "Local source", "External source", "None of the above"], answer: "Internal source" },
  { q: "External sources of finance include except", options: ["Bank overdraft", "Trade credit", "Trade factoring", "Provision for depreciation"], answer: "Provision for depreciation" },
  { q: "System where asset is rented on contract by company is", options: ["Trade credit", "Trade factoring", "Equipment Leasing", "Sale of asset"], answer: "Equipment Leasing" },
  { q: "Redeemable long term loans from individuals/organizations is", options: ["Shares", "Mortgage Debentures", "Loans", "Business loan"], answer: "Mortgage Debentures" },
  { q: "Management function concerned with people is", options: ["Production Function", "Finance Function", "Personnel Function", "Marketing Function"], answer: "Personnel Function" },
  { q: "Personnel function includes except", options: ["Manpower Planning", "Performance Appraisal", "Labour Relation", "Acquisition of Loan"], answer: "Acquisition of Loan" }
  { q: "Supply and demand of human resources in accordance with manpower requirements is called", options: ["Manpower Planning", "Labour Relation", "Performance Appraisal", "Career Development"], answer: "Manpower Planning" },
  { q: "Sources of manpower requirements are", options: ["Local & Foreign", "Internal & External", "Micro & Macro", "Maximum & Minimum"], answer: "Internal & External" },
  { q: "Recruitment of employees already working in different positions is called", options: ["Micro Source", "Medium Source", "External Source", "Internal Source"], answer: "Internal Source" },
  { q: "Advantage of internal recruitment is", options: ["Increases advertising cost", "Cheaper as external adverts not required", "Brings new skills", "Enables hiring of competitors’ staff"], answer: "Cheaper as external adverts not required" },
  { q: "Recruitment discouraging injection of new blood is", options: ["Internal Recruitment", "Local Recruitment", "External Recruitment", "Macro Recruitment"], answer: "Internal Recruitment" },
  { q: "Recruitment outside organization for vacant post is called", options: ["External Recruitment", "Internal Recruitment", "Medium Recruitment", "Full Recruitment"], answer: "External Recruitment" },
  { q: "Benefit of external recruitment is", options: ["Lowers adverts cost", "Opportunity to acquire new skills", "Time conscious", "Motivates existing workers"], answer: "Opportunity to acquire new skills" },
  { q: "Business strategy moving out of current specialization into new areas is called", options: ["Diversification", "Development", "Specialisation", "Research"], answer: "Diversification" },
  { q: "Main reasons for diversifying include except", options: ["Spread business risks", "Achieve greater profits", "Make use of by-products", "Coordinating R&D marketing"], answer: "Coordinating R&D marketing" },
  { q: "Business strategy concentrating on narrow range of products to exploit niche is called", options: ["Production", "Product Specialisation", "Diversification", "Product Marketing"], answer: "Product Specialisation" },
  { q: "Deals with problems of providing goods and services to satisfy specific groups", options: ["Production", "Marketing", "Distribution", "Promotion"], answer: "Marketing" },
  { q: "Marketing is the performance of business activities directing flow of goods to satisfy customers according to", options: ["McCarthy", "British Chartered Institute of Marketing", "Fayol", "Terry"], answer: "McCarthy" },
  { q: "Function responsible for distribution of goods and services from manufacturer to users", options: ["Distribution Function", "Transportation Function", "Personnel Function", "Marketing Function"], answer: "Marketing Function" },
  { q: "Support services facilitating production process are called", options: ["Production Planning", "Production Function", "Production Administration", "Production Ancillaries"], answer: "Production Ancillaries" },
  { q: "Activity ensuring company standards of quality are met is called", options: ["Investigation", "Inspection", "Research", "Development"], answer: "Inspection" },
  { q: "Purpose of inspection includes", options: ["Ensure quality standards", "Ensure raw materials quality", "Avoid wastage", "All of the above"], answer: "All of the above" },
  { q: "Which is not a form of inspection", options: ["Floor", "Time", "Price", "Place"], answer: "Price" },
  { q: "Strategy to get product to point of purchase by final users is", options: ["Distribution Strategy", "Selling Strategy", "Purchase Strategy", "Promotion Strategy"], answer: "Distribution Strategy" },
  { q: "Recruitment process begins with", options: ["Induction", "Recruitment", "Job Analysis", "Selection"], answer: "Job Analysis" },
  { q: "Formalized review of how individual performs job is", options: ["Industrial Relation", "Performance Appraisal", "Labour Relation", "Job Review"], answer: "Performance Appraisal" },
  { q: "Training is closely linked to", options: ["Performance Appraisal", "Performance Measurement", "Performance Analysis", "Performance Ratio"], answer: "Performance Appraisal" },
  { q: "Forms of training include", options: ["Induction Training", "Skill Training", "Human Relation Training", "All of the above"], answer: "All of the above" },
  { q: "Teaching people how to do work while actually doing it is called", options: ["On the Job Training", "Off the Job Training", "Process Training", "System Training"], answer: "On the Job Training" },
  { q: "Acquisition of new skills outside worker's company premises is called", options: ["On the Job Training", "Off the Job Training", "External Training", "Knowledge Training"], answer: "Off the Job Training" },
  { q: "Training for newly employed workers is", options: ["Skill Training", "Induction Training", "Management Training", "Executive Development"], answer: "Induction Training" },
  { q: "Training to develop ability to handle specific tasks is", options: ["Management Training", "Skill Training", "Induction Training", "Human Relations Training"], answer: "Skill Training" },
  { q: "Development of attitude and ability to deal with people is", options: ["Human Relation Training", "Skill Training", "Induction Training", "Management Training"], answer: "Human Relation Training" },
  { q: "Training of employees for management positions is", options: ["Induction Training", "Skill Training", "Management Training", "Executive Development"], answer: "Management Training" },
  { q: "Training for managers to develop personal abilities and skills is", options: ["Executive Development", "Technical Training", "Management Training", "Human Relation Training"], answer: "Executive Development" },
  { q: "Employee safety and welfare is part of", options: ["Production Function", "Personnel Function", "Promotion Function", "Payment Function"], answer: "Personnel Function" },
  { q: "Wages and salaries administration is associated with", options: ["Personal Function", "Personnel Function", "Promotion Function", "Payment Function"], answer: "Personnel Function" },
  { q: "Training process comprises except", options: ["Identification of individual training needs", "Design and implementation", "Evaluation of training program", "Salary Administration"], answer: "Salary Administration" },
  { q: "Capital is defined as", options: ["Money available to invest", "Prohibitive cost of entry", "Guarantee that company will be successful", "A & B"], answer: "Money available to invest" },
  { q: "Business plan includes", options: ["Financial info, production plans, personnel policies", "Goals of business and how to achieve", "Step by step plan for success", "All of the above"], answer: "All of the above" },
  { q: "Who is an entrepreneur?", options: ["Someone investing time and money", "Someone who makes a lot of money", "Someone taking risk to make profit", "Both A & C"], answer: "Both A & C" },
  { q: "Define Free Enterprise", options: ["Business taking risk to make profit", "Program by Government", "People in business trying to make profit", "Business adventure/undertaking"], answer: "Business taking risk to make profit" },
  { q: "Quality control is defined as", options: ["Controlling cost", "Controlling number produced", "Producing & monitoring products acceptable to consumer", "Producing & monitoring products acceptable to workers"], answer: "Producing & monitoring products acceptable to consumer" },
  { q: "Market survey is important because it tells", options: ["How many & what type of people shop", "What customer will buy", "How much customer will pay", "All of the above"], answer: "All of the above" },
  { q: "Making an unplanned purchase is called", options: ["Consumer shopping", "Warranty", "Impulse buying", "Comparison shopping"], answer: "Impulse buying" },
  { q: "Product planning tells you", options: ["Where you will produce", "Cost to produce", "Net profit", "Revenue"], answer: "Cost to produce" },
  { q: "Gross profit is", options: ["Amount of money you get for profit lab", "Amount collected from selling products", "Amount product costs to produce", "Has nothing to do with money"], answer: "Amount of money you get for profit lab" },
  { q: "Net profit is", options: ["Amount of money you get for profit lab", "Amount collected from selling products", "Amount product costs to produce", "Has nothing to do with money"], answer: "Amount collected from selling products" },
  { q: "To figure gross profit:", options: ["Add ticket sales", "Add ticket sales minus cost of ingredients", "Add cost minus total sales", "Add cost + total sales"], answer: "Add ticket sales minus cost of ingredients" },
  { q: "To figure net profit:", options: ["Add ticket sales", "Add ticket sales minus cost of ingredients", "Add cost minus total sales", "Add cost + total sales"], answer: "Add ticket sales minus cost of ingredients" },
  { q: "Operating at a profit is any activity providing goods and services according to", options: ["Mack N.T", "Fry", "Nickel", "Terry"], answer: "Nickel" },
  { q: "Private enterprise system is also known as", options: ["Socialism", "Capitalism", "Mixed system", "None of the above"], answer: "Capitalism" }
  { q: "Every observation should be forwarded to (09020329969). Prior proper preparation prevents poor performance. This emphasizes", options: ["Planning", "Execution", "Assessment", "Evaluation"], answer: "Planning" },
  { q: "Which of these is a commercial activity of business?", options: ["Purchasing", "Selling", "Transporting", "All of the above"], answer: "All of the above" },
  { q: "Which of these is a technical activity of business?", options: ["Manufacturing", "Advertising", "Distribution", "Accounting"], answer: "Manufacturing" },
  { q: "Which of these is a financial activity?", options: ["Raising capital", "Production", "Sales", "Marketing"], answer: "Raising capital" },
  { q: "Which of these is a managerial activity?", options: ["Planning", "Operating machines", "Transporting goods", "Hiring staff"], answer: "Planning" },
  { q: "Which of these is a personnel activity?", options: ["Recruitment", "Distribution", "Sales", "Advertising"], answer: "Recruitment" },
  { q: "Major objective of business apart from profit includes", options: ["Social responsibility", "Marketing only", "R&D only", "Nothing"], answer: "Social responsibility" },
  { q: "Business that satisfies consumer needs directly is called", options: ["Consumer business", "Producer business", "Service business", "Industrial business"], answer: "Consumer business" },
  { q: "Business process ends with", options: ["Customer satisfaction", "Collection of revenue", "Production", "Advertising"], answer: "Collection of revenue" },
  { q: "Which of these is a human resource?", options: ["Employees", "Machinery", "Money", "Land"], answer: "Employees" },
  { q: "Natural resources in business include", options: ["Water", "Oil", "Land", "All of the above"], answer: "All of the above" },
  { q: "Innovation as an objective of business means", options: ["Introducing new products or methods", "Increasing staff", "Advertising more", "Hiring more managers"], answer: "Introducing new products or methods" },
  { q: "Flexibility in business refers to", options: ["Ability to adapt to market changes", "Ability to increase profit", "Ability to hire more employees", "Ability to advertise"], answer: "Ability to adapt to market changes" },
  { q: "Responsiveness in business means", options: ["Quickly reacting to customer demand", "Managing finances", "Advertising products", "Producing more goods than needed"], answer: "Quickly reacting to customer demand" },
  { q: "Cost minimization in business involves", options: ["Reducing production, inventory, transport, and warehousing costs", "Increasing marketing only", "Hiring more staff", "Investing in competitors"], answer: "Reducing production, inventory, transport, and warehousing costs" },
  { q: "Service level optimization in business aims to", options: ["Deliver the right product, at the right time, to the right place", "Reduce staff salaries", "Produce more than needed", "Avoid customer complaints"], answer: "Deliver the right product, at the right time, to the right place" },
  { q: "Industrial Revolution increased", options: ["Mass production", "Manual labour only", "Small scale businesses", "Nothing"], answer: "Mass production" },
  { q: "Industrial Entrepreneur's role was", options: ["Organizing resources for large scale production", "Teaching only", "Marketing products", "Hiring workers only"], answer: "Organizing resources for large scale production" },
  { q: "Production era emphasized", options: ["Efficiency in production", "Marketing", "Customer preference", "None"], answer: "Efficiency in production" },
  { q: "Marketing era emphasized", options: ["Customer satisfaction", "Mass production", "Labor efficiency", "Cost minimization"], answer: "Customer satisfaction" },
  { q: "Relationship era emphasized", options: ["Building long term links with customers and employees", "Cost cutting", "Producing more goods", "Advertising aggressively"], answer: "Building long term links with customers and employees" },
  { q: "Personnel function involves", options: ["Recruitment, training, safety and welfare", "Production planning", "Financial planning", "Marketing"], answer: "Recruitment, training, safety and welfare" },
  { q: "Finance function ensures", options: ["Funds are available for organizational activities", "Goods are produced", "Marketing is done", "Staff are trained"], answer: "Funds are available for organizational activities" },
  { q: "Production management ensures", options: ["Efficient and effective conversion of inputs to outputs", "Marketing is optimized", "Finance is controlled", "Human resources are reduced"], answer: "Efficient and effective conversion of inputs to outputs" },
  { q: "Batch production is used when", options: ["Goods are produced in batches to meet stock or specific orders", "Goods are customized for single customer", "Goods are produced continuously", "Goods are not produced"], answer: "Goods are produced in batches to meet stock or specific orders" },
  { q: "Mass production is best for", options: ["Large quantities of identical goods", "Single custom orders", "Small batches", "Service provision only"], answer: "Large quantities of identical goods" },
  { q: "Job production is", options: ["Producing goods individually as per customer order", "Producing mass goods", "Producing batches", "Producing semi-finished goods"], answer: "Producing goods individually as per customer order" },
  { q: "Process production involves", options: ["Highly automated and continuous production", "Manual batch production", "Job production", "Retail business"], answer: "Highly automated and continuous production" },
  { q: "Work study aims to", options: ["Establish optimum work methods", "Control financial resources", "Market goods", "Manage HR"], answer: "Establish optimum work methods" },
  { q: "Method study involves", options: ["Designing efficient work methods", "Measuring output only", "Financial management", "Marketing research"], answer: "Designing efficient work methods" },
  { q: "Work measurement determines", options: ["Time required for a qualified worker to perform a task", "Profit margins", "Customer satisfaction", "Advertising effectiveness"], answer: "Time required for a qualified worker to perform a task" },
  { q: "Human resource planning ensures", options: ["Organization has required manpower", "Finances are controlled", "Goods are produced", "Marketing is effective"], answer: "Organization has required manpower" },
  { q: "Internal recruitment means", options: ["Hiring from within the organization", "Hiring outside", "Recruiting internationally", "Using headhunters only"], answer: "Hiring from within the organization" },
  { q: "External recruitment brings", options: ["New skills and ideas", "Old ideas", "Lower cost only", "Fewer options"], answer: "New skills and ideas" },
  { q: "Financial sources internal include", options: ["Retention of profit", "Bank overdraft", "Trade credit", "Loans"], answer: "Retention of profit" },
  { q: "Financial sources external include", options: ["Bank loans, trade credit, leasing", "Retention of profit", "Savings", "None"], answer: "Bank loans, trade credit, leasing" },
  { q: "Gross profit calculation involves", options: ["Total revenue minus cost of goods sold", "Total revenue only", "Cost of goods only", "Profit only"], answer: "Total revenue minus cost of goods sold" },
  { q: "Net profit calculation involves", options: ["Gross profit minus expenses", "Revenue only", "Cost only", "Profit only"], answer: "Gross profit minus expenses" },
  { q: "Private enterprise system emphasizes", options: ["Capitalism", "Socialism", "Mixed economy", "Government control"], answer: "Capitalism" },
  { q: "Free enterprise allows", options: ["Business to operate freely to make profit", "Government to control everything", "No competition", "Fixed prices"], answer: "Business to operate freely to make profit" },
  { q: "An entrepreneur is someone who", options: ["Takes risks and organizes resources for profit", "Only invests money", "Only works for others", "Avoids risks"], answer: "Takes risks and organizes resources for profit" },
  { q: "Quality control ensures", options: ["Products meet acceptable standards for consumers", "Employees are happy", "Profit is maximized only", "Production is reduced"], answer: "Products meet acceptable standards for consumers" },
  { q: "Market survey provides", options: ["Consumer preferences, quantity, and price willingness", "Production data only", "Financial data only", "HR data only"], answer: "Consumer preferences, quantity, and price willingness" },
  { q: "Impulse buying occurs when", options: ["Customer purchases unplanned item", "Customer buys a planned item", "Retailer sells to another retailer", "Nothing"], answer: "Customer purchases unplanned item" },
  { q: "Product planning helps determine", options: ["Cost, materials, production location", "Marketing only", "Staff recruitment only", "Finance only"], answer: "Cost, materials, production location" },
  { q: "Industrial entrepreneur role is mainly", options: ["Organizing resources and managing production", "Marketing products", "Training staff only", "Research only"], answer: "Organizing resources and managing production" },
  { q: "Personnel function includes", options: ["Recruitment, training, wages, welfare", "Finance only", "Production only", "Marketing only"], answer: "Recruitment, training, wages, welfare" },
  { q: "Training improves", options: ["Skills, efficiency, and employee growth", "Production only", "Marketing only", "Finance only"], answer: "Skills, efficiency, and employee growth" },
  { q: "Executive development focuses on", options: ["Developing managerial and personal abilities", "Physical labor only", "Advertising", "Sales only"], answer: "Developing managerial and personal abilities" }
  { q: "The activities that ensure minimum quality standards are met include", options: ["Inspection", "Production only", "Marketing only", "Finance only"], answer: "Inspection" },
  { q: "Inspection helps to", options: ["Avoid wastage, ensure quality of raw materials, maintain standards", "Hire staff", "Reduce marketing cost", "Increase revenue"], answer: "Avoid wastage, ensure quality of raw materials, maintain standards" },
  { q: "Which of these is a form of inspection?", options: ["Floor, Time, Place", "Price only", "Marketing only", "Finance only"], answer: "Floor, Time, Place" },
  { q: "Distribution strategy aims to", options: ["Get product to final consumer efficiently", "Increase cost of production", "Reduce employee welfare", "Limit marketing"], answer: "Get product to final consumer efficiently" },
  { q: "Job analysis in recruitment helps to", options: ["Identify job requirements and skills", "Hire externally only", "Produce goods", "Increase profits"], answer: "Identify job requirements and skills" },
  { q: "Performance appraisal is", options: ["Reviewing employee's job performance formally", "Training employees", "Marketing products", "Producing goods"], answer: "Reviewing employee's job performance formally" },
  { q: "Induction training is for", options: ["Newly employed workers", "Managers only", "Executives only", "Marketing staff only"], answer: "Newly employed workers" },
  { q: "Skill training focuses on", options: ["Specific tasks", "Management only", "Marketing only", "Finance only"], answer: "Specific tasks" },
  { q: "Human relation training develops", options: ["Ability to deal effectively with people", "Production skills only", "Financial skills only", "Marketing skills only"], answer: "Ability to deal effectively with people" },
  { q: "Management training is for", options: ["Employees preparing for management roles", "Induction only", "Executives only", "Production staff only"], answer: "Employees preparing for management roles" },
  { q: "Executive development focuses on", options: ["Advanced management skills and personal development", "Basic training only", "Marketing skills only", "Production skills only"], answer: "Advanced management skills and personal development" },
  { q: "Employee safety and welfare function is part of", options: ["Personnel function", "Finance function", "Marketing function", "Production function"], answer: "Personnel function" },
  { q: "Wages and salaries administration belongs to", options: ["Personnel function", "Finance function", "Marketing function", "Production function"], answer: "Personnel function" },
  { q: "Capital in business refers to", options: ["Money available to invest", "Staff only", "Land only", "Machines only"], answer: "Money available to invest" },
  { q: "Business plan includes", options: ["Financial info, production plans, personnel policies, goals and step by step plan", "Marketing only", "Finance only", "Production only"], answer: "Financial info, production plans, personnel policies, goals and step by step plan" },
  { q: "An entrepreneur is", options: ["Someone who invests, takes risks, and organizes resources for profit", "Someone who avoids risk", "Someone who works for others", "Someone who produces goods only"], answer: "Someone who invests, takes risks, and organizes resources for profit" },
  { q: "Free enterprise system allows", options: ["Business to operate freely and compete to make profit", "Government control only", "No competition", "Fixed pricing"], answer: "Business to operate freely and compete to make profit" },
  { q: "Quality control ensures", options: ["Products meet consumer standards", "Marketing success only", "Finance success only", "Nothing"], answer: "Products meet consumer standards" },
  { q: "Market survey helps to know", options: ["Consumer type, quantity demanded, price willingness", "Production cost only", "Profit only", "Employee performance only"], answer: "Consumer type, quantity demanded, price willingness" },
  { q: "Impulse buying is", options: ["Unplanned purchase by consumer", "Planned purchase only", "Buying in bulk only", "Marketing strategy only"], answer: "Unplanned purchase by consumer" },
  { q: "Product planning helps determine", options: ["Cost, materials, location of production", "Marketing only", "HR only", "Finance only"], answer: "Cost, materials, location of production" },
  { q: "Gross profit formula is", options: ["Total revenue minus cost of goods sold", "Revenue only", "Cost only", "Profit only"], answer: "Total revenue minus cost of goods sold" },
  { q: "Net profit formula is", options: ["Gross profit minus expenses", "Revenue only", "Cost only", "Profit only"], answer: "Gross profit minus expenses" },
  { q: "Industrial revolution led to", options: ["Mass production using semi-skilled labor and machines", "Small-scale craft only", "Handmade goods only", "Manual labor only"], answer: "Mass production using semi-skilled labor and machines" },
  { q: "Production era emphasized", options: ["Efficiency and maximizing production", "Customer satisfaction only", "Marketing only", "Finance only"], answer: "Efficiency and maximizing production" },
  { q: "Marketing era emphasized", options: ["Customer satisfaction and demand orientation", "Production only", "Finance only", "HR only"], answer: "Customer satisfaction and demand orientation" },
  { q: "Relationship era emphasized", options: ["Long-term links with customers and employees", "Profit only", "Marketing only", "Production only"], answer: "Long-term links with customers and employees" },
  { q: "Batch production is", options: ["Producing goods in batches to meet demand or stock", "Producing single custom orders", "Producing continuously", "Producing semi-finished goods"], answer: "Producing goods in batches to meet demand or stock" },
  { q: "Job production is", options: ["Producing goods individually for specific customer order", "Producing mass goods", "Producing batches", "Producing semi-finished goods"], answer: "Producing goods individually for specific customer order" },
  { q: "Mass production is", options: ["Continuous production of large quantities of identical goods", "Producing single custom orders", "Producing small batches", "Service provision only"], answer: "Continuous production of large quantities of identical goods" },
  { q: "Process production is", options: ["Highly automated, complex production as extension of mass production", "Batch production", "Job production", "Service provision"], answer: "Highly automated, complex production as extension of mass production" },
  { q: "Work study aims to", options: ["Optimize work methods", "Reduce profit", "Market products only", "Manage finance only"], answer: "Optimize work methods" },
  { q: "Method study is", options: ["Establishing best work methods", "Measuring output only", "Marketing research only", "Financial planning only"], answer: "Establishing best work methods" },
  { q: "Work measurement determines", options: ["Time for qualified worker to perform task", "Profit margin only", "Marketing efficiency only", "Production output only"], answer: "Time for qualified worker to perform task" },
  { q: "Human resource planning ensures", options: ["Correct manpower for organization", "Marketing only", "Finance only", "Production only"], answer: "Correct manpower for organization" },
  { q: "Internal recruitment hires", options: ["From within organization", "Externally only", "From other companies only", "From foreign countries only"], answer: "From within organization" },
  { q: "External recruitment brings", options: ["New skills and ideas", "Old knowledge only", "Lower cost only", "Fewer options"], answer: "New skills and ideas" },
  { q: "Internal financial sources include", options: ["Retention of profit", "Bank loans", "Trade credit", "Leasing"], answer: "Retention of profit" },
  { q: "External financial sources include", options: ["Bank loans, trade credit, leasing", "Retention of profit", "Savings", "None"], answer: "Bank loans, trade credit, leasing" },
  { q: "Private enterprise system is", options: ["Capitalism", "Socialism", "Mixed economy", "Government controlled"], answer: "Capitalism" },
  { q: "Entrepreneur takes", options: ["Risks, organizes resources for profit", "No risk", "Works for others only", "Avoids investment"], answer: "Risks, organizes resources for profit" },
  { q: "Quality control ensures", options: ["Products meet consumer standards", "Employee satisfaction only", "Profit only", "Marketing only"], answer: "Products meet consumer standards" },
  { q: "Market survey informs", options: ["Consumer type, quantity, and price willingness", "Production only", "HR only", "Finance only"], answer: "Consumer type, quantity, and price willingness" },
  { q: "Impulse buying occurs when", options: ["Consumer purchases unplanned item", "Consumer purchases planned item", "Retailers buy only", "Advertising fails"], answer: "Consumer purchases unplanned item" },
  { q: "Product planning helps determine", options: ["Cost, materials, production location", "Marketing only", "HR only", "Finance only"], answer: "Cost, materials, production location" },
  { q: "Gross profit formula is", options: ["Total revenue minus cost of goods sold", "Revenue only", "Cost only", "Profit only"], answer: "Total revenue minus cost of goods sold" },
  { q: "Net profit formula is", options: ["Gross profit minus expenses", "Revenue only", "Cost only", "Profit only"], answer: "Gross profit minus expenses" },
  { q: "Industrial revolution led to", options: ["Mass production using machines and semi-skilled labor", "Handmade goods only", "Manual labor only", "Small scale craft only"], answer: "Mass production using machines and semi-skilled labor" },
  { q: "Production era emphasized", options: ["Efficiency and maximizing production", "Marketing only", "Finance only", "HR only"], answer: "Efficiency and maximizing production" },
  { q: "Marketing era emphasized", options: ["Customer satisfaction and demand orientation", "Production only", "Finance only", "HR only"], answer: "Customer satisfaction and demand orientation" },
  { q: "Relationship era emphasized", options: ["Long-term links with customers and employees", "Profit only", "Marketing only", "Production only"], answer: "Long-term links with customers and employees" },
  { q: "Personnel function includes", options: ["Recruitment, training, wages, welfare", "Production only", "Finance only", "Marketing only"], answer: "Recruitment, training, wages, welfare" },
  { q: "Training improves", options: ["Skills, efficiency, employee growth", "Production only", "Marketing only", "Finance only"], answer: "Skills, efficiency, employee growth" },
  { q: "Executive development focuses on", options: ["Managerial and personal abilities", "Physical labor only", "Marketing only", "Production only"], answer: "Managerial and personal abilities" }
];
